Make it easy for people to play the games
Seniru/cli-games pull request #70
Opened 2019-12-10 02:14 UTC by AllAwesome497

I made a script that uses your script and lets the user play the games on repl.it, this will direct the user to it.

2019-12-10 08:19 UTC, Seniru commented
Hmm... Nice suggestion!

2019-12-10 08:47 UTC, Seniru commented
@AllAwesome497 thanks for contributing! This idea is awesome as it let people to play the games without worrying about cloning this repo to their machines.

I tested this game with repl.it and I found some problems with this. It doesn't load the game correctly and throws an error.

Here is an example

```sh
what game
Hangman
MazeEscape
TextAdventures
TicTacToe
Hangman
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/runner/Hangman/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
exit status 1
```

Hope you could fix this problem. Also make the prompt more friendly (I think you know what I mean :P). Otherwise this is good! 👏

2019-12-10 08:48 UTC, Seniru requested changes
Changes requested. More info can be found in the conversation

2019-12-13 02:21 UTC, AllAwesome497 commented
Let me try and fix it

2019-12-13 02:25 UTC, AllAwesome497 commented
Ok i fixed it, the only thing I have added to it is a simple bash script to let the user choose which game they want to play (I also renamed a few files to simplify it)

2019-12-13 02:26 UTC, AllAwesome497 commented
Here is the bash script in case you want to see it:
```bash
npm i prompts; npm i ansi-escapes; echo Which game do you want to play?; echo Hangman; echo MazeEscape; echo TextAdventures; echo TicTacToe; read game; node $game/index.js```

2019-12-13 03:42 UTC, Seniru commented on README.md
> +[![Run on Repl.it](https://repl.it/badge/github/salifm/cli-games)](https://repl.it/@AllAwesome497/cli-games)
I suppose this should link to the main repo (salif's one)

2019-12-13 03:44 UTC, Seniru requested changes
I think the badge should link to the repl of this repository. Other than that the work is perfect!
I think you can fix this small problem and the PR would be merged soon!

2019-12-13 12:53 UTC, AllAwesome497 commented
Wdym? [![Run on Repl.it](https://repl.it/badge/github/salifm/cli-games)](https://repl.it/@AllAwesome497/cli-games) goes straight to a fork of this repository, and it should pull commits from it also.

2019-12-13 13:02 UTC, Seniru commented
The badge links to your repository instead of salif's one. That should be corrected ☺

2019-12-13 13:04 UTC, AllAwesome497 commented
As far as I know salif does not have a repl for it. If they would like to i'd be happy to help them set it up though.

2019-12-13 13:05 UTC, AllAwesome497 commented
Basically that repl just pulls from this repo.

2019-12-13 16:17 UTC, AllAwesome497 commented
Oh and in my repl it still credits salifm, just so u know.

2019-12-13 16:23 UTC, salif approved these changes

2019-12-14 03:29 UTC, Seniru commented
I just want to make sure the repl get updated when there are changes to salif's repo. If yes, then this PR will get merged.

2019-12-14 12:41 UTC, AllAwesome497 commented
I can say for certain that it works every time if u make a selection menu to run the games. I'll make an addition to my run script later to make sure it automatically pulls and then runs it.

2019-12-14 12:55 UTC, Seniru commented
OK! I'll merge this. Inform me after you did the script

2019-12-14 12:56 UTC, Seniru approved these changes
Approved!

2019-12-14 12:56 UTC, merged

2019-12-14 12:57 UTC, Seniru commented
Enjoy 🎉🎉🎉